
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-config
data:
  ansible.cfg: |
    [defaults]
    host_key_checking = False
    timeout = 30
    inventory = /app/inventory/inventory.ini
    remote_user = infadm
    log_path = /app/logs/ansible.log
    become = True
    become_method = sudo
    become_user = infadm
    
    [privilege_escalation]
    become = True
    become_method = sudo
    become_user = infadm
    
    [ssh_connection]
    pipelining = True
    control_path = /tmp/ansible-ssh-%%h-%%p-%%r
