
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fix-deployment-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fix-deployment-orchestrator
  template:
    metadata:
      labels:
        app: fix-deployment-orchestrator
    spec:
      containers:
        - name: fix-deployment-orchestrator
          image: fix-deployment-orchestrator:latest
          ports:
            - containerPort: 5000
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "false"
            - name: LOG_FILE_PATH
              value: "/app/logs/application.log"
            - name: DEPLOYMENT_LOGS_DIR
              value: "/app/logs"
          volumeMounts:
            - name: fix-files-volume
              mountPath: /app/fixfiles
            - name: ssh-keys-volume
              mountPath: /root/.ssh
            - name: ansible-config-volume
              mountPath: /etc/ansible
            - name: inventory-volume
              mountPath: /app/inventory
            - name: app-logs-volume
              mountPath: /app/logs
      volumes:
        - name: fix-files-volume
          persistentVolumeClaim:
            claimName: fix-files-pvc
        - name: ssh-keys-volume
          secret:
            secretName: ssh-keys
            defaultMode: 0600
        - name: ansible-config-volume
          configMap:
            name: ansible-config
            defaultMode: 0644
        - name: inventory-volume
          configMap:
            name: inventory-config
        - name: app-logs-volume
          persistentVolumeClaim:
            claimName: app-logs-pvc
